<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20__cxa_vec_new2%20and%20deallocation%20functions%20that%20throw%20exceptions&In-Reply-To=%3C200305150713.AAA26133%40hpcll183.cup.hp.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="001714.html">
   <LINK REL="Next"  HREF="001716.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions</H1>
    <B>Dennis Handly</B> 
    <A HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20__cxa_vec_new2%20and%20deallocation%20functions%20that%20throw%20exceptions&In-Reply-To=%3C200305150713.AAA26133%40hpcll183.cup.hp.com%3E"
       TITLE="[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that throw exceptions">dhandly at cup.hp.com
       </A><BR>
    <I>Thu May 15 07:13:57 UTC 2003</I>
    <P><UL>
        <LI>Previous message: <A HREF="001714.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that	throw exceptions
</A></li>
        <LI>Next message: <A HREF="001716.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that	throw exceptions
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1715">[ date ]</a>
              <a href="thread.html#1715">[ thread ]</a>
              <a href="subject.html#1715">[ subject ]</a>
              <a href="author.html#1715">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>&gt;<i>[except.terminate]
</I>&gt;<i>  --when the exception handling mechanism, after completing evaluation
</I>&gt;<i>    of the expression to be thrown but before the exception is caught
</I>&gt;<i>    (_except.throw_), calls a user function that exits via an uncaught
</I>&gt;<i>    exception,1)
</I>
So what does uncaught exception mean?  Any exception without a handler?
(That footnote needs to be expanded.)

Or anytime you throw when uncaught_exception is true, 18.6.4(2)?

This disallows throws that are caught locally in destructors, while
unwinding.  Or is this not &quot;exiting&quot;, so legal?

&gt;<i>The exception has not yet been caught.  The exception-handling mechanism
</I>&gt;<i>calls a user function (the deallocation routine) which exits via an exception.
</I>Mark Mitchell

I wasn't clear what uncaught exception meant and whether &quot;nesting&quot; of throw
is allowed.

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="001714.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that	throw exceptions
</A></li>
	<LI>Next message: <A HREF="001716.html">[cxx-abi-dev] __cxa_vec_new2 and deallocation functions that	throw exceptions
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#1715">[ date ]</a>
              <a href="thread.html#1715">[ thread ]</a>
              <a href="subject.html#1715">[ subject ]</a>
              <a href="author.html#1715">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">More information about the cxx-abi-dev
mailing list</a><br>
</body></html>
