<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw Processing
   </TITLE>
   <LINK REL="Index" HREF="index.html" >
   <LINK REL="made" HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20Details%20missing%20for%20EH%202.4.1%20Overview%20of%20Throw%0A%20Processing&In-Reply-To=%3C7FDC0DB0-E96A-40B4-87BC-19DAAC2256F2%40apple.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000019.html">
   <LINK REL="Next"  HREF="000021.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw Processing</H1>
    <B>John McCall</B> 
    <A HREF="mailto:cxx-abi-dev%40codesourcery.com?Subject=Re%3A%20%5Bcxx-abi-dev%5D%20Details%20missing%20for%20EH%202.4.1%20Overview%20of%20Throw%0A%20Processing&In-Reply-To=%3C7FDC0DB0-E96A-40B4-87BC-19DAAC2256F2%40apple.com%3E"
       TITLE="[cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw Processing">rjmccall at apple.com
       </A><BR>
    <I>Tue Dec 20 18:29:13 UTC 2011</I>
    <P><UL>
        <LI>Previous message: <A HREF="000019.html">[cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw	Processing
</A></li>
        <LI>Next message: <A HREF="000021.html">[cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw	Processing
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#48">[ date ]</a>
              <a href="thread.html#48">[ thread ]</a>
              <a href="subject.html#48">[ subject ]</a>
              <a href="author.html#48">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>On Dec 19, 2011, at 7:58 PM, Dennis Handly wrote:
&gt;&gt;<i> From: John McCall &lt;<A HREF="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">rjmccall at apple.com</A>&gt;
</I>&gt;&gt;&gt;<i> Does the last sentence mean that if there is a catch for what the copy
</I>&gt;&gt;&gt;<i> constructor is throwing, it is ignored?
</I>&gt;<i> 
</I>&gt;&gt;<i> I think this is just the ABI document being out-of-date vs. the standard.
</I>&gt;&gt;<i> DR 475 jumped around a lot, but the final resolution (March 2010) makes
</I>&gt;&gt;<i> it clear that we are *not* supposed to call std::terminate if an exception
</I>&gt;&gt;<i> is thrown during the copy-initialization of an exception object.
</I>&gt;<i> 
</I>&gt;<i> So we just go to whatever catch is active or std::terminate?
</I>
Right.  It's no longer special in any way, except that if you've allocated
an exception object (in Itanium-like exception schemes) you need to free it.

&gt;<i> But in any case, the copy constructor seems to be elided for both aC++ and
</I>&gt;<i> g++.
</I>
Right.  One of the nice things about the change is that it no longer calls
out the final copy-construction as having special exception semantics,
which means you can now reasonably do copy-elision here.  I know many
compilers were doing it before anyway, with the special semantics also
being elided away.

&gt;&gt;<i> We only terminate if an exception is thrown after the initialization is
</I>&gt;&gt;<i> complete, e.g.  by a destructor of that full-expression,
</I>&gt;<i> 
</I>&gt;<i> So does this need to be mentioned for __cxa_end_catch or is it the generated
</I>&gt;<i> cleanup code for the throw?
</I>
I don't know what you mean.  __cxa_end_catch is not required
as part of the generated code for a throw expression.  I don't think it
ever was.

&gt;<i> Since copy constructor seems to be elided, there is no cleanup code for the
</I>&gt;<i> throw.  (Unless some complex conditions or lots of temps?  But these wouldn't
</I>&gt;<i> be the full-expression.)
</I>
Once you've called __cxa_allocate_exception, you must either throw
it or free it.

&gt;<i> g++ seems to not disallow that throw in __cxa_end_catch.
</I>&gt;<i> aC++ does too but does get lost if a catch is present.
</I>
In general, the generated call to __cxa_end_catch at the end of a
catch clause can throw.  You can prove that it can't in some cases,
based on the caught exception object type or the CFG of the catch
clause.

John.

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000019.html">[cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw	Processing
</A></li>
	<LI>Next message: <A HREF="000021.html">[cxx-abi-dev] Details missing for EH 2.4.1 Overview of Throw	Processing
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#48">[ date ]</a>
              <a href="thread.html#48">[ thread ]</a>
              <a href="subject.html#48">[ subject ]</a>
              <a href="author.html#48">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="http://sourcerytools.com/cgi-bin/mailman/listinfo/cxx-abi-dev">More information about the cxx-abi-dev
mailing list</a><br>
</body></html>
